// 한자 단어 데이터 (자동 생성: data/words.json → 이 파일)
// 수정은 data/words.json 을 고친 뒤 `npm run build:words` 로 재생성하세요.

export const WORDS = [
  {
    kanji: "会計",
    jp: "かいけい",
    kr: "카이케이",
    koReading: "회계",
    koMeaning: "자금 흐름을 기록하고 정리하는 것.",
    jpMeaning: "(상점에서 하는) '계산', '결제' 의미도 있음.",
  },
  {
    kanji: "割愛",
    jp: "かつあい",
    kr: "카츠아이",
    koReading: "할애",
    koMeaning: "(시간이나 노력을) 내어줌, 빼내어 씀.",
    jpMeaning: "(아쉽지만) 생략함, 빼버림, 버림.",
  },
  {
    kanji: "真面目",
    jp: "まじめ",
    kr: "마지메",
    koReading: "진면목",
    koMeaning: "(본래 갖고 있던, 숨겨져 있던) 진짜 모습.",
    jpMeaning: "성실함, 얌전함, 진지함.",
  },
  {
    kanji: "気分",
    jp: "きぶん",
    kr: "키분",
    koReading: "기분",
    koMeaning: "감정 상태, 심리 상태.",
    jpMeaning: "감정 상태 + 신체 컨디션도 가능.",
  },
  {
    kanji: "人参",
    jp: "にんじん",
    kr: "닌진",
    koReading: "인삼",
    koMeaning: "인삼 (약재, 한반도의 오랜 특산품).",
    jpMeaning: "당근 (식재료).",
  },
  {
    kanji: "物件",
    jp: "ぶっけん",
    kr: "붓켄",
    koReading: "물건",
    koMeaning: "(손에 들 수 있는) 물건 그 자체.",
    jpMeaning: "부동산 매물 (아파트, 방, 토지 등).",
  },
  {
    kanji: "愛人",
    jp: "あいじん",
    kr: "아이진",
    koReading: "애인",
    koMeaning: "연인, 사랑하는 사람.",
    jpMeaning: "불륜 상대!",
  },
  {
    kanji: "放心",
    jp: "ほうしん",
    kr: "호우신",
    koReading: "방심",
    koMeaning: "부주의함, 주의를 게을리 함.",
    jpMeaning: "넋을 잃음, 멍하니 있음.",
  },
  {
    kanji: "独断",
    jp: "どくだん",
    kr: "도쿠단",
    koReading: "독단",
    koMeaning: "혼자서 결정함 (다소 부정적 뉘앙스).",
    jpMeaning: "소신껏 판단함 (다소 긍정적 뉘앙스).",
  },
  {
    kanji: "工作",
    jp: "こうさく",
    kr: "코우사쿠",
    koReading: "공작",
    koMeaning: "음모를 꾸밈 (비밀스럽고 어두운 일 뉘앙스).",
    jpMeaning: "가공, 만들기 (어두운 뉘앙스 X, 만들기 수업도 '공작').",
  },
  {
    kanji: "工夫",
    jp: "くふう",
    kr: "쿠후-",
    koReading: "공부",
    koMeaning: "학습, 무언가 배우는 것.",
    jpMeaning: "아이디어를 냄, 고안함, 궁리함.",
  },
  {
    kanji: "自慢",
    jp: "じまん",
    kr: "지만",
    koReading: "자만",
    koMeaning: "자만, 자신감이 지나친 것 (부정적 뉘앙스).",
    jpMeaning: "자랑 (한국 의미보다 긍정적인 뉘앙스가 있음).",
  },
  {
    kanji: "適当",
    jp: "てきとう",
    kr: "테키토-",
    koReading: "적당",
    koMeaning: "딱 알맞음, 과하거나 부족하지 않음.",
    jpMeaning: "딱 알맞음, 대충대충.",
  },
  {
    kanji: "心術",
    jp: "しんじゅつ",
    kr: "신쥬츠",
    koReading: "심술",
    koMeaning: "심술, 괴롭히거나 시기하는 것.",
    jpMeaning: "마음가짐, 마음씨, 성품.",
  },
  {
    kanji: "旅館",
    jp: "りょかん",
    kr: "료칸",
    koReading: "여관",
    koMeaning: "저가형 숙소.",
    jpMeaning: "일본 전식 숙소 (저렴하다는 이미지 X).",
  },
  {
    kanji: "多情",
    jp: "たじょう",
    kr: "타죠-",
    koReading: "다정",
    koMeaning: "정이 많음, 따뜻하고 친절함.",
    jpMeaning: "바람기가 많음, 정을 쉽게 줌.",
  },
  {
    kanji: "大丈夫",
    jp: "だいじょうぶ",
    kr: "다이죠-부",
    koReading: "대장부",
    koMeaning: "건장하고 호탕한 사나이.",
    jpMeaning: "괜찮아, 문제 없어.",
  },
  {
    kanji: "八方美人",
    jp: "はっぽうびじん",
    kr: "합뽀-비진",
    koReading: "팔방미인",
    koMeaning: "이것 저것 잘하는 사람.",
    jpMeaning: "이리저리 눈치 보며 줏대 없는 사람.",
  },
];

export const WORD_TOTAL = WORDS.length;
