// 단어 데이터 (자동 생성: data/words.json → 이 파일)
// 수정은 data/words.json 을 고친 뒤 `npm run build:words` 로 재생성하세요.

export const WORDS = [
  {
    kanji: "会計",
    jp: "かいけい",
    kr: "카이케이",
    koReading: "회계",
    koMeaning: "자금 흐름을 기록하고 정리하는 것.",
    jpMeaning: "(상점에서 하는) '계산', '결제' 의미도 있음.",
  },
  {
    kanji: "割愛",
    jp: "かつあい",
    kr: "카츠아이",
    koReading: "할애",
    koMeaning: "(시간이나 노력을) 내어줌, 빼내어 씀.",
    jpMeaning: "(아쉽지만) 생략함, 빼버림, 버림.",
  },
  {
    kanji: "真面目",
    jp: "まじめ",
    kr: "마지메",
    koReading: "진면목",
    koMeaning: "(본래 갖고 있던, 숨겨져 있던) 진짜 모습.",
    jpMeaning: "성실함, 얌전함, 진지함.",
  },
  {
    kanji: "気分",
    jp: "きぶん",
    kr: "키분",
    koReading: "기분",
    koMeaning: "감정 상태, 심리 상태.",
    jpMeaning: "감정 상태 + 신체 컨디션도 가능.",
  },
  {
    kanji: "人参",
    jp: "にんじん",
    kr: "닌진",
    koReading: "인삼",
    koMeaning: "인삼 (약재, 한반도의 오랜 특산품).",
    jpMeaning: "당근 (식재료).",
  },
  {
    kanji: "物件",
    jp: "ぶっけん",
    kr: "붓켄",
    koReading: "물건",
    koMeaning: "(손에 들 수 있는) 물건 그 자체.",
    jpMeaning: "부동산 매물 (아파트, 방, 토지 등).",
  },
  {
    kanji: "愛人",
    jp: "あいじん",
    kr: "아이진",
    koReading: "애인",
    koMeaning: "연인, 사랑하는 사람.",
    jpMeaning: "불륜 상대!",
  },
  {
    kanji: "放心",
    jp: "ほうしん",
    kr: "호우신",
    koReading: "방심",
    koMeaning: "부주의함, 주의를 게을리 함.",
    jpMeaning: "넋을 잃음, 멍하니 있음.",
  },
  {
    kanji: "独断",
    jp: "どくだん",
    kr: "도쿠단",
    koReading: "독단",
    koMeaning: "혼자서 결정함 (다소 부정적 뉘앙스).",
    jpMeaning: "소신껏 판단함 (다소 긍정적 뉘앙스).",
  },
  {
    kanji: "工作",
    jp: "こうさく",
    kr: "코우사쿠",
    koReading: "공작",
    koMeaning: "음모를 꾸밈 (비밀스럽고 어두운 일 뉘앙스).",
    jpMeaning: "가공, 만들기 (어두운 뉘앙스 X, 만들기 수업도 '공작').",
  },
  {
    kanji: "工夫",
    jp: "くふう",
    kr: "쿠후-",
    koReading: "공부",
    koMeaning: "학습, 무언가 배우는 것.",
    jpMeaning: "아이디어를 냄, 고안함, 궁리함.",
  },
  {
    kanji: "自慢",
    jp: "じまん",
    kr: "지만",
    koReading: "자만",
    koMeaning: "자만, 자신감이 지나친 것 (부정적 뉘앙스).",
    jpMeaning: "자랑 (한국 의미보다 긍정적인 뉘앙스가 있음).",
  },
  {
    kanji: "適当",
    jp: "てきとう",
    kr: "테키토-",
    koReading: "적당",
    koMeaning: "딱 알맞음, 과하거나 부족하지 않음.",
    jpMeaning: "딱 알맞음, 대충대충.",
  },
  {
    kanji: "心術",
    jp: "しんじゅつ",
    kr: "신쥬츠",
    koReading: "심술",
    koMeaning: "심술, 괴롭히거나 시기하는 것.",
    jpMeaning: "마음가짐, 마음씨, 성품.",
  },
  {
    kanji: "旅館",
    jp: "りょかん",
    kr: "료칸",
    koReading: "여관",
    koMeaning: "저가형 숙소.",
    jpMeaning: "일본 전식 숙소 (저렴하다는 이미지 X).",
  },
  {
    kanji: "多情",
    jp: "たじょう",
    kr: "타죠-",
    koReading: "다정",
    koMeaning: "정이 많음, 따뜻하고 친절함.",
    jpMeaning: "바람기가 많음, 정을 쉽게 줌.",
  },
  {
    kanji: "大丈夫",
    jp: "だいじょうぶ",
    kr: "다이죠-부",
    koReading: "대장부",
    koMeaning: "건장하고 호탕한 사나이.",
    jpMeaning: "괜찮아, 문제 없어.",
  },
  {
    kanji: "八方美人",
    jp: "はっぽうびじん",
    kr: "합뽀-비진",
    koReading: "팔방미인",
    koMeaning: "이것 저것 잘하는 사람.",
    jpMeaning: "이리저리 눈치 보며 줏대 없는 사람.",
  },
  {
    kanji: "空港",
    jp: "くうこう",
    kr: "쿠-코-",
    koReading: "공항",
    meaning: "비행기를 타고 내리는 곳.",
    scene: "공항·전철에서",
  },
  {
    kanji: "飛行機",
    jp: "ひこうき",
    kr: "히코-키",
    koReading: "비행기",
    meaning: "하늘을 나는 교통수단.",
    scene: "공항·전철에서",
  },
  {
    kanji: "電車",
    jp: "でんしゃ",
    kr: "덴샤",
    koReading: "전철",
    meaning: "도시 안팎을 잇는 철도 교통수단.",
    scene: "공항·전철에서",
  },
  {
    kanji: "新幹線",
    jp: "しんかんせん",
    kr: "신칸센",
    koReading: "신칸센",
    meaning: "일본의 고속철도.",
    scene: "공항·전철에서",
  },
  {
    kanji: "切符",
    jp: "きっぷ",
    kr: "킷푸",
    koReading: "표(승차권)",
    meaning: "전철·버스를 탈 때 필요한 티켓.",
    scene: "공항·전철에서",
  },
  {
    kanji: "改札口",
    jp: "かいさつぐち",
    kr: "카이사츠구치",
    koReading: "개찰구",
    meaning: "역에서 표를 확인하고 지나가는 곳.",
    scene: "공항·전철에서",
  },
  {
    kanji: "乗り換え",
    jp: "のりかえ",
    kr: "노리카에",
    koReading: "환승",
    meaning: "다른 노선으로 갈아타는 것.",
    scene: "공항·전철에서",
  },
  {
    kanji: "タクシー",
    jp: "タクシー",
    kr: "타쿠시-",
    koReading: "택시",
    meaning: "돈을 내고 타는 자동차.",
    scene: "공항·전철에서",
  },
  {
    kanji: "バス停",
    jp: "バスてい",
    kr: "바스테이",
    koReading: "버스 정류장",
    meaning: "버스를 기다리는 곳.",
    scene: "공항·전철에서",
  },
  {
    kanji: "荷物",
    jp: "にもつ",
    kr: "니모츠",
    koReading: "짐",
    meaning: "여행 가방 등 들고 다니는 물건.",
    scene: "공항·전철에서",
  },
  {
    kanji: "パスポート",
    jp: "パスポート",
    kr: "파스포-토",
    koReading: "여권",
    meaning: "해외여행에 꼭 필요한 신분증.",
    scene: "공항·전철에서",
  },
  {
    kanji: "出口",
    jp: "でぐち",
    kr: "데구치",
    koReading: "출구",
    meaning: "밖으로 나가는 문.",
    scene: "공항·전철에서",
  },
  {
    kanji: "宿泊",
    jp: "しゅくはく",
    kr: "슈쿠하쿠",
    koReading: "숙박",
    meaning: "잠을 자며 머무는 것.",
    scene: "숙소에서",
  },
  {
    kanji: "予約",
    jp: "よやく",
    kr: "요야쿠",
    koReading: "예약",
    meaning: "미리 자리·방을 잡아두는 것.",
    scene: "숙소에서",
  },
  {
    kanji: "部屋",
    jp: "へや",
    kr: "헤야",
    koReading: "방",
    meaning: "잠을 자는 공간.",
    scene: "숙소에서",
  },
  {
    kanji: "鍵",
    jp: "かぎ",
    kr: "카기",
    koReading: "열쇠",
    meaning: "문을 잠그고 여는 도구.",
    scene: "숙소에서",
  },
  {
    kanji: "温泉",
    jp: "おんせん",
    kr: "온센",
    koReading: "온천",
    meaning: "땅에서 나오는 뜨거운 물로 하는 목욕.",
    scene: "숙소에서",
  },
  {
    kanji: "大浴場",
    jp: "だいよくじょう",
    kr: "다이요쿠죠-",
    koReading: "대욕장",
    meaning: "여러 명이 함께 쓰는 큰 욕탕.",
    scene: "숙소에서",
  },
  {
    kanji: "フロント",
    jp: "フロント",
    kr: "후론토",
    koReading: "프런트",
    meaning: "숙소의 접수처.",
    scene: "숙소에서",
  },
  {
    kanji: "チェックイン",
    jp: "チェックイン",
    kr: "첵쿠인",
    koReading: "체크인",
    meaning: "숙소에 들어가는 수속.",
    scene: "숙소에서",
  },
  {
    kanji: "食堂",
    jp: "しょくどう",
    kr: "쇼쿠도-",
    koReading: "식당",
    meaning: "밥을 사 먹는 곳.",
    scene: "식당·카페에서",
  },
  {
    kanji: "居酒屋",
    jp: "いざかや",
    kr: "이자카야",
    koReading: "이자카야",
    meaning: "술과 안주를 파는 일본식 술집.",
    scene: "식당·카페에서",
  },
  {
    kanji: "注文",
    jp: "ちゅうもん",
    kr: "츄-몬",
    koReading: "주문",
    meaning: "음식을 시키는 것.",
    scene: "식당·카페에서",
  },
  {
    kanji: "お会計",
    jp: "おかいけい",
    kr: "오카이케이",
    koReading: "계산",
    meaning: "음식값을 치르는 것.",
    scene: "식당·카페에서",
  },
  {
    kanji: "領収書",
    jp: "りょうしゅうしょ",
    kr: "료-슈-쇼",
    koReading: "영수증",
    meaning: "돈을 낸 기록이 적힌 종이(경비 처리용).",
    scene: "식당·카페에서",
  },
  {
    kanji: "メニュー",
    jp: "メニュー",
    kr: "메뉴-",
    koReading: "메뉴",
    meaning: "음식 목록.",
    scene: "식당·카페에서",
  },
  {
    kanji: "お冷",
    jp: "おひや",
    kr: "오히야",
    koReading: "냉수",
    meaning: "차가운 물(식당에서 무료로 주는 물).",
    scene: "식당·카페에서",
  },
  {
    kanji: "お通し",
    jp: "おとおし",
    kr: "오토-시",
    koReading: "기본 안주",
    meaning: "이자카야에서 자릿세처럼 먼저 나오는 작은 안주.",
    scene: "식당·카페에서",
  },
  {
    kanji: "定食",
    jp: "ていしょく",
    kr: "테이쇼쿠",
    koReading: "정식",
    meaning: "밥·국·반찬이 세트로 나오는 식사.",
    scene: "식당·카페에서",
  },
  {
    kanji: "割り箸",
    jp: "わりばし",
    kr: "와리바시",
    koReading: "나무젓가락",
    meaning: "쪼개 쓰는 일회용 젓가락.",
    scene: "식당·카페에서",
  },
  {
    kanji: "持ち帰り",
    jp: "もちかえり",
    kr: "모치카에리",
    koReading: "포장(테이크아웃)",
    meaning: "음식을 가지고 나가는 것.",
    scene: "식당·카페에서",
  },
  {
    kanji: "禁煙",
    jp: "きんえん",
    kr: "킨엔",
    koReading: "금연",
    meaning: "담배를 피우면 안 되는 것.",
    scene: "식당·카페에서",
  },
  {
    kanji: "買い物",
    jp: "かいもの",
    kr: "카이모노",
    koReading: "쇼핑",
    meaning: "물건을 사는 것.",
    scene: "쇼핑할 때",
  },
  {
    kanji: "免税",
    jp: "めんぜい",
    kr: "멘제이",
    koReading: "면세",
    meaning: "세금을 안 내는 것(외국인 여행자 혜택).",
    scene: "쇼핑할 때",
  },
  {
    kanji: "レジ",
    jp: "レジ",
    kr: "레지",
    koReading: "계산대",
    meaning: "돈을 내는 곳.",
    scene: "쇼핑할 때",
  },
  {
    kanji: "お土産",
    jp: "おみやげ",
    kr: "오미야게",
    koReading: "기념품",
    meaning: "여행지에서 사 가는 선물.",
    scene: "쇼핑할 때",
  },
  {
    kanji: "試着",
    jp: "しちゃく",
    kr: "시챠쿠",
    koReading: "시착(입어보기)",
    meaning: "옷을 사기 전에 입어보는 것.",
    scene: "쇼핑할 때",
  },
  {
    kanji: "割引",
    jp: "わりびき",
    kr: "와리비키",
    koReading: "할인",
    meaning: "값을 깎아주는 것.",
    scene: "쇼핑할 때",
  },
  {
    kanji: "現金",
    jp: "げんきん",
    kr: "겐킨",
    koReading: "현금",
    meaning: "카드가 아닌 실제 돈.",
    scene: "쇼핑할 때",
  },
  {
    kanji: "クレジットカード",
    jp: "クレジットカード",
    kr: "쿠레짓토카-도",
    koReading: "신용카드",
    meaning: "카드로 결제하는 수단.",
    scene: "쇼핑할 때",
  },
  {
    kanji: "袋",
    jp: "ふくろ",
    kr: "후쿠로",
    koReading: "봉투(비닐봉지)",
    meaning: "물건을 담는 봉지.",
    scene: "쇼핑할 때",
  },
  {
    kanji: "店員",
    jp: "てんいん",
    kr: "텐인",
    koReading: "점원",
    meaning: "가게에서 일하는 사람.",
    scene: "쇼핑할 때",
  },
  {
    kanji: "地図",
    jp: "ちず",
    kr: "치즈",
    koReading: "지도",
    meaning: "길을 찾을 때 보는 그림.",
    scene: "관광·길찾기",
  },
  {
    kanji: "道",
    jp: "みち",
    kr: "미치",
    koReading: "길",
    meaning: "사람이 다니는 곳.",
    scene: "관광·길찾기",
  },
  {
    kanji: "案内所",
    jp: "あんないじょ",
    kr: "안나이죠",
    koReading: "안내소",
    meaning: "정보를 물어볼 수 있는 곳.",
    scene: "관광·길찾기",
  },
  {
    kanji: "神社",
    jp: "じんじゃ",
    kr: "진쟈",
    koReading: "신사",
    meaning: "일본 고유 종교(신토)의 참배 장소.",
    scene: "관광·길찾기",
  },
  {
    kanji: "お寺",
    jp: "おてら",
    kr: "오테라",
    koReading: "절(사찰)",
    meaning: "불교 참배 장소.",
    scene: "관광·길찾기",
  },
  {
    kanji: "展望台",
    jp: "てんぼうだい",
    kr: "텐보-다이",
    koReading: "전망대",
    meaning: "높은 곳에서 경치를 보는 곳.",
    scene: "관광·길찾기",
  },
  {
    kanji: "写真",
    jp: "しゃしん",
    kr: "샤신",
    koReading: "사진",
    meaning: "카메라로 찍는 것.",
    scene: "관광·길찾기",
  },
  {
    kanji: "入場料",
    jp: "にゅうじょうりょう",
    kr: "뉴-죠-료-",
    koReading: "입장료",
    meaning: "들어갈 때 내는 돈.",
    scene: "관광·길찾기",
  },
  {
    kanji: "休憩",
    jp: "きゅうけい",
    kr: "큐-케이",
    koReading: "휴게(휴식)",
    meaning: "잠깐 쉬는 것.",
    scene: "관광·길찾기",
  },
  {
    kanji: "迷子",
    jp: "まいご",
    kr: "마이고",
    koReading: "미아",
    meaning: "길을 잃어버린 것(또는 그 사람).",
    scene: "관광·길찾기",
  },
  {
    kanji: "病院",
    jp: "びょういん",
    kr: "뵤-인",
    koReading: "병원",
    meaning: "아플 때 가는 곳.",
    scene: "아프거나 급할 때",
  },
  {
    kanji: "薬局",
    jp: "やっきょく",
    kr: "얏쿄쿠",
    koReading: "약국",
    meaning: "약을 파는 곳.",
    scene: "아프거나 급할 때",
  },
  {
    kanji: "救急車",
    jp: "きゅうきゅうしゃ",
    kr: "큐-큐-샤",
    koReading: "구급차",
    meaning: "응급환자를 실어 나르는 차.",
    scene: "아프거나 급할 때",
  },
  {
    kanji: "熱",
    jp: "ねつ",
    kr: "네츠",
    koReading: "열(발열)",
    meaning: "몸에서 나는 열.",
    scene: "아프거나 급할 때",
  },
  {
    kanji: "頭痛",
    jp: "ずつう",
    kr: "즈츠-",
    koReading: "두통",
    meaning: "머리가 아픈 것.",
    scene: "아프거나 급할 때",
  },
  {
    kanji: "保険",
    jp: "ほけん",
    kr: "호켄",
    koReading: "보험",
    meaning: "사고·병에 대비하는 제도.",
    scene: "아프거나 급할 때",
  },
  {
    kanji: "警察",
    jp: "けいさつ",
    kr: "케이사츠",
    koReading: "경찰",
    meaning: "안전을 지키는 사람들.",
    scene: "아프거나 급할 때",
  },
  {
    kanji: "落とし物",
    jp: "おとしもの",
    kr: "오토시모노",
    koReading: "분실물",
    meaning: "잃어버린 물건.",
    scene: "아프거나 급할 때",
  },
  {
    kanji: "コンビニ",
    jp: "コンビニ",
    kr: "콘비니",
    koReading: "편의점",
    meaning: "24시간 여는 작은 가게.",
    scene: "편의점에서",
  },
  {
    kanji: "お弁当",
    jp: "おべんとう",
    kr: "오벤토-",
    koReading: "도시락",
    meaning: "미리 담아둔 한 끼 식사.",
    scene: "편의점에서",
  },
  {
    kanji: "温める",
    jp: "あたためる",
    kr: "아타타메루",
    koReading: "데우다",
    meaning: "음식을 따뜻하게 만드는 것.",
    scene: "편의점에서",
  },
  {
    kanji: "レシート",
    jp: "レシート",
    kr: "레시-토",
    koReading: "영수증",
    meaning: "산 물건의 기록이 적힌 종이.",
    scene: "편의점에서",
  },
  {
    kanji: "賞味期限",
    jp: "しょうみきげん",
    kr: "쇼-미키겐",
    koReading: "유통기한",
    meaning: "맛있게 먹을 수 있는 기한.",
    scene: "편의점에서",
  },
  {
    kanji: "支払い",
    jp: "しはらい",
    kr: "시하라이",
    koReading: "지불",
    meaning: "돈을 내는 것.",
    scene: "편의점에서",
  },
  {
    kanji: "天気",
    jp: "てんき",
    kr: "텐키",
    koReading: "날씨",
    meaning: "그날의 기상 상태.",
    scene: "날씨·일정 이야기할 때",
  },
  {
    kanji: "傘",
    jp: "かさ",
    kr: "카사",
    koReading: "우산",
    meaning: "비를 막는 도구.",
    scene: "날씨·일정 이야기할 때",
  },
  {
    kanji: "暑い",
    jp: "あつい",
    kr: "아츠이",
    koReading: "덥다",
    meaning: "기온이 높은 상태.",
    scene: "날씨·일정 이야기할 때",
  },
  {
    kanji: "寒い",
    jp: "さむい",
    kr: "사무이",
    koReading: "춥다",
    meaning: "기온이 낮은 상태.",
    scene: "날씨·일정 이야기할 때",
  },
  {
    kanji: "予定",
    jp: "よてい",
    kr: "요테이",
    koReading: "예정(일정)",
    meaning: "하기로 정해 둔 계획.",
    scene: "날씨·일정 이야기할 때",
  },
  {
    kanji: "時間",
    jp: "じかん",
    kr: "지칸",
    koReading: "시간",
    meaning: "시각이나 기간.",
    scene: "날씨·일정 이야기할 때",
  },
  {
    kanji: "無料",
    jp: "むりょう",
    kr: "무료-",
    koReading: "무료",
    meaning: "돈을 안 내도 되는 것.",
    scene: "생활 전반",
  },
  {
    kanji: "有料",
    jp: "ゆうりょう",
    kr: "유-료-",
    koReading: "유료",
    meaning: "돈을 내야 하는 것.",
    scene: "생활 전반",
  },
  {
    kanji: "充電",
    jp: "じゅうでん",
    kr: "쥬-덴",
    koReading: "충전",
    meaning: "배터리에 전기를 채우는 것.",
    scene: "생활 전반",
  },
  {
    kanji: "Wi-Fi",
    jp: "ワイファイ",
    kr: "와이화이",
    koReading: "와이파이",
    meaning: "무선 인터넷.",
    scene: "생활 전반",
  },
  {
    kanji: "トイレ",
    jp: "トイレ",
    kr: "토이레",
    koReading: "화장실",
    meaning: "용변을 보는 곳.",
    scene: "생활 전반",
  },
  {
    kanji: "喫煙所",
    jp: "きつえんじょ",
    kr: "키츠엔죠",
    koReading: "흡연소",
    meaning: "담배를 피울 수 있는 곳.",
    scene: "생활 전반",
  },
  {
    kanji: "両替",
    jp: "りょうがえ",
    kr: "료-가에",
    koReading: "환전",
    meaning: "다른 나라 돈으로 바꾸는 것.",
    scene: "생활 전반",
  },
  {
    kanji: "自動販売機",
    jp: "じどうはんばいき",
    kr: "지도-한바이키",
    koReading: "자판기",
    meaning: "돈을 넣으면 물건이 나오는 기계.",
    scene: "생활 전반",
  },
  {
    kanji: "忘れ物",
    jp: "わすれもの",
    kr: "와스레모노",
    koReading: "분실물(놓고 온 물건)",
    meaning: "깜빡 두고 온 물건.",
    scene: "생활 전반",
  },
  {
    kanji: "満員",
    jp: "まんいん",
    kr: "만인",
    koReading: "만원(꽉 참)",
    meaning: "자리가 꽉 차서 더 못 들어가는 상태.",
    scene: "생활 전반",
  },
];

export const WORD_TOTAL = WORDS.length;
